// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDtZBeyok5-M2SckatwgLOhy5-EYP-mrQ',
    appId: '1:841524044418:web:884f8b15996a3131a50a9b',
    messagingSenderId: '841524044418',
    projectId: 'easy-chat-b5e5a',
    authDomain: 'easy-chat-b5e5a.firebaseapp.com',
    storageBucket: 'easy-chat-b5e5a.firebasestorage.app',
    measurementId: 'G-R4C8BGLZ6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNUlf8mVL4WR6o1P2hRWEJts-TQwFRlLE',
    appId: '1:841524044418:android:cc75773f6bfa44a8a50a9b',
    messagingSenderId: '841524044418',
    projectId: 'easy-chat-b5e5a',
    storageBucket: 'easy-chat-b5e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxuF3vjSiP3Fg_eePVGj65aRujACJo2Zo',
    appId: '1:841524044418:ios:c7c2fb691e476a48a50a9b',
    messagingSenderId: '841524044418',
    projectId: 'easy-chat-b5e5a',
    storageBucket: 'easy-chat-b5e5a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxuF3vjSiP3Fg_eePVGj65aRujACJo2Zo',
    appId: '1:841524044418:ios:c7c2fb691e476a48a50a9b',
    messagingSenderId: '841524044418',
    projectId: 'easy-chat-b5e5a',
    storageBucket: 'easy-chat-b5e5a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDtZBeyok5-M2SckatwgLOhy5-EYP-mrQ',
    appId: '1:841524044418:web:9ee76d2be0b39426a50a9b',
    messagingSenderId: '841524044418',
    projectId: 'easy-chat-b5e5a',
    authDomain: 'easy-chat-b5e5a.firebaseapp.com',
    storageBucket: 'easy-chat-b5e5a.firebasestorage.app',
    measurementId: 'G-LQ91KXQ6M0',
  );
}
